name: test 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  PRIMARY_NODE_VERSION: 12

jobs:
  tests:
    name: Tests 
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.PRIMARY_NODE_VERSION }}

    - name: Install dependencies
      run: |
        yarn --ignore-engines --frozen-lockfile --ignore-scripts
        #yarn lerna:init
        yarn check:clean-workspace-after-install
    - name: Build
      run: |
        yarn build
    
    - name: Publish code coverage report
      uses: codecov/codecov-action@v1
      with:
        yml: ./codecov.yml
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittest
        name: codecov
